#ifndef TOKENS_HPP
#define TOKENS_HPP

#include<string>

// these are the tokens as specified in the 1990 ansi
// excluding preprocessing tokens
enum TokenType
{
    None,
    Operator,
    constant,
    identifier,
    keyword,
    string,
    punctuator
};

union TokenValue
{
    std::string *text;
};

extern TokenValue yylval; // function for handing the value to yacc

extern int yylex(); // lexer function generated by flex, returns token type

#endif
